"""
app_simulator/offline/train_drain.py
======================================
One-time script: trains Drain3 on simulator's own output/logs.csv.

Run ONLY if you want to retrain on new simulator data.
For initial boot, the pre-trained drain_state.bin from
d:\\AIOps_Incident_Management\\DEVOPS\\ is already copied into models/.

Usage:
    cd d:\\AIOps_Incident_Management
    python backend/nodes/classification/train_drain.py

Prerequisites:
    pip install drain3
    app_simulator/output/logs.csv  (generated by run_simulator.py)

Output:
    app_simulator/models/drain_state.bin          (Drain3 state)
    app_simulator/models/known_log_templates.json (template IDs seen in training)
"""
from __future__ import annotations
import json
import os
import sys
import pickle
from pathlib import Path

import pandas as pd
from sklearn.model_selection import train_test_split

_HERE = Path(__file__).resolve().parent.parent.parent
sys.path.insert(0, str(_HERE))

from Simulator.app_data_generator_for_offline.config import (
    DRAIN_INI, DRAIN_STATE, KNOWN_TEMPLATES_JSON, OUTPUT_DIR, MODELS_DIR,
)

RANDOM_SEED = 42
TEST_SIZE   = 0.20


def load_logs(logs_csv: Path) -> pd.DataFrame:
    print(f"[Drain3] Loading {logs_csv} ...")
    df = pd.read_csv(logs_csv, dtype=str).fillna("")
    df = df.drop_duplicates()
    df = df.sort_values(["episode_id", "timestamp"]).reset_index(drop=True)
    print(f"  Rows: {len(df):,}  |  Episodes: {df['episode_id'].nunique():,}")
    return df


def train(df: pd.DataFrame) -> tuple:
    """Episode-stratified 80/20 split, train on 80%, validate on 20%."""
    from drain3 import TemplateMiner
    from drain3.template_miner_config import TemplateMinerConfig
    from drain3.file_persistence import FilePersistence

    # Episode-level split (not row-level) to avoid data leakage
    episodes = df["episode_id"].unique()
    ep_labels = df.drop_duplicates("episode_id").set_index("episode_id")["failure_mode"]
    train_eps, test_eps = train_test_split(
        episodes, test_size=TEST_SIZE, random_state=RANDOM_SEED,
        stratify=[ep_labels.get(e, "NONE") for e in episodes],
    )

    train_df = df[df["episode_id"].isin(train_eps)]
    test_df  = df[df["episode_id"].isin(test_eps)]
    print(f"  Train episodes: {len(train_eps)}  ({len(train_df):,} rows)")
    print(f"  Test  episodes: {len(test_eps)}   ({len(test_df):,} rows)")

    # Load Drain3 config
    config = TemplateMinerConfig()
    if DRAIN_INI.exists():
        config.load(str(DRAIN_INI))
    config.drain_sim_th        = 0.4
    config.drain_depth         = 4
    config.drain_max_children  = 100
    config.snapshot_interval_minutes = 0

    DRAIN_STATE.parent.mkdir(parents=True, exist_ok=True)
    persistence = FilePersistence(str(DRAIN_STATE))
    miner = TemplateMiner(persistence_handler=persistence, config=config)

    print("\n[Drain3] Training on training episodes ...")
    for _, row in train_df.iterrows():
        msg = str(row.get("log_message", "")).strip()
        if msg:
            miner.add_log_message(msg)

    known_ids = {c.cluster_id for c in miner.drain.clusters}
    print(f"  Clusters (templates) learned: {len(known_ids)}")

    # Save known template IDs
    with KNOWN_TEMPLATES_JSON.open("w", encoding="utf-8") as f:
        json.dump(sorted(known_ids), f, indent=2)
    print(f"  Saved known_log_templates.json ({len(known_ids)} IDs)")

    # Validate on test split
    print("\n[Drain3] Validating on test episodes ...")
    novel_count = 0
    total_count = 0
    for _, row in test_df.iterrows():
        msg = str(row.get("log_message", "")).strip()
        if not msg:
            continue
        total_count += 1
        cluster = miner.match(msg)
        if cluster is None or cluster.cluster_id not in known_ids:
            novel_count += 1

    fp_rate = novel_count / max(total_count, 1)
    print(f"  Test logs    : {total_count:,}")
    print(f"  Novel (FP)   : {novel_count:,}  ({fp_rate * 100:.1f}%)")

    threshold = 0.05
    if fp_rate <= threshold:
        print(f"  [PASS] FP rate {fp_rate * 100:.1f}% <= {threshold * 100:.0f}%")
    else:
        print(f"  [WARN] FP rate {fp_rate * 100:.1f}% > {threshold * 100:.0f}% — consider lowering sim_th in drain3.ini")

    return miner, known_ids


def main() -> None:
    logs_csv = OUTPUT_DIR / "logs.csv"
    if not logs_csv.exists():
        print(f"[ERROR] {logs_csv} not found.")
        print("  Run the simulator first:  python app_simulator/run_simulator.py MEMORY_LEAK")
        sys.exit(1)

    print("=" * 60)
    print("  Drain3 Template Training")
    print("=" * 60)
    df = load_logs(logs_csv)
    miner, known_ids = train(df)

    print("\n" + "=" * 60)
    print("  Training complete.")
    print(f"  drain_state.bin          : {DRAIN_STATE}")
    print(f"  known_log_templates.json : {KNOWN_TEMPLATES_JSON}")
    print("=" * 60)


if __name__ == "__main__":
    main()
