"""
app_data_generator/config.py
==============================
Central configuration for the AIOps Backend.
All paths, column definitions, failure modes, and tuning constants live here.
No file ever hardcodes a path, mode name, or threshold.
"""
from pathlib import Path

# ── Root directories ──────────────────────────────────────────────────────────
BACKEND_DIR          = Path(__file__).resolve().parent.parent.parent   # d:/AIOps_Incident_Management/backend
APP_DATA_DIR         = BACKEND_DIR / "Simulator" / "app_data_generator_for_offline"
NODES_DIR            = BACKEND_DIR / "Inference_langgraph" / "nodes"
OUTPUT_DIR           = APP_DATA_DIR / "output"

# ── Database (generated by run_simulator.py) ──────────────────────────────────
DB_PATH              = APP_DATA_DIR / "output" / "simulator_db.sqlite"

# ── Trained model artifacts (classification node) ────────────────────────────
MODELS_DIR           = NODES_DIR / "classification" / "models"
LGBM_MODEL_PKL       = MODELS_DIR / "lgbm_model.pkl"
LABEL_ENCODER_PKL    = MODELS_DIR / "label_encoder.pkl"
FEATURE_NAMES_JSON   = MODELS_DIR / "feature_names.json"

# ── Drain3 artifacts (classification node) ───────────────────────────────────
DRAIN_INI            = MODELS_DIR / "drain3.ini"
DRAIN_STATE          = MODELS_DIR / "drain_state.bin"
KNOWN_TEMPLATES_JSON = MODELS_DIR / "known_log_templates.json"
PNML_DIR             = MODELS_DIR / "process_models"
# ── Severity thresholds path ───────────────────────────────────────────────
SEVERITY_THRESHOLDS   = NODES_DIR / "preliminary_severity" / "severity_config" / "thresholds.yaml"


# ── Per-node output paths ─────────────────────────────────────────────────────
FEATURE_ENG_OUTPUT_DIR     = NODES_DIR / "feature_engineering" / "output"
PRELIM_SEVERITY_OUTPUT_DIR = NODES_DIR / "preliminary_severity" / "output"
CLASSIFICATION_OUTPUT_DIR  = NODES_DIR / "classification" / "output"
TUMBLING_WINDOW_OUTPUT_DIR = NODES_DIR / "tumbling_window" / "output"
FORECASTING_OUTPUT_DIR     = NODES_DIR / "forecasting" / "output"
SEVERITY_UPDATE_OUTPUT_DIR = NODES_DIR / "severity_update" / "output"
HUMAN_GATE_OUTPUT_DIR      = NODES_DIR / "human_gate"       / "output"

# ── Named output CSV files ────────────────────────────────────────────────────
ENGINEERED_FEAT_CSV    = FEATURE_ENG_OUTPUT_DIR    / "engineered_features.csv"
PRELIM_SEVERITY_CSV    = PRELIM_SEVERITY_OUTPUT_DIR / "preliminary_severity.csv"
PIPELINE_RESULTS_CSV   = CLASSIFICATION_OUTPUT_DIR  / "pipeline_results.csv"
TUMBLING_WINDOW_CSV    = TUMBLING_WINDOW_OUTPUT_DIR / "tumbling_window_output.csv"
FORECASTING_OUTPUT_CSV = FORECASTING_OUTPUT_DIR     / "forecasting_output.csv"
SEVERITY_UPDATE_CSV    = SEVERITY_UPDATE_OUTPUT_DIR / "severity_update_output.csv"
HUMAN_GATE_OUTPUT_CSV  = HUMAN_GATE_OUTPUT_DIR      / "human_gate_output.csv"
HUMAN_GATE_AUDIT_DB    = HUMAN_GATE_OUTPUT_DIR      / "human_gate_audit.db"

# ── Human Gate tuning ─────────────────────────────────────────────────────────
# Seconds before auto-approve fires when no operator response is received.
# v1 default: 2 seconds (fast enough for demo, slow enough to actually click).
# Increase to 30-60 for production use.
HUMAN_GATE_TIMEOUT_SECONDS: int = 2

# ── Legacy aliases (kept for backward compatibility) ─────────────────────────
PIPELINE_OUTPUT_DIR  = CLASSIFICATION_OUTPUT_DIR   # most runners use this

# ── Auto-train ────────────────────────────────────────────────────────────────
MIN_TRAIN_ROWS: int | None = None

# ── Classifier training split constants ───────────────────────────────────────
# Fraction of data reserved as a held-out test set (never seen during tuning).
TEST_SIZE: float = 0.20
# Global random seed used across train/test split, StratifiedKFold, and Optuna.
RANDOM_SEED: int = 42

# ── Episode to simulate (CLI default) ────────────────────────────────────────
EPISODE = "MEMORY_LEAK"

# ── Playback speed ────────────────────────────────────────────────────────────
SPEED = 1.0

# ── Noise level (fractional jitter on all metric values) ─────────────────────
NOISE_LEVEL = 0.04          # +-4%

# ── Simulation timing ────────────────────────────────────────────────────────
STEP_INTERVAL_SECONDS = 2.0
MAX_STEPS             = 120
STEPS_PER_EPISODE     = 120

# ── Multi-mode data generation ────────────────────────────────────────────────
EPISODES_PER_MODE     = 77
TARGET_ROWS           = 120_120

# ── Tumbling window ───────────────────────────────────────────────────────────
WINDOW_SIZE           = 10

# ── Feature engineering ───────────────────────────────────────────────────────
FE_TRIGGER_EVERY      = 10
ROLLING_WINDOW        = 30

# ── Classifier feature columns ────────────────────────────────────────────────
RAW_METRIC_FEATURE_COLS = [
    "cpu_utilization", "memory_utilization", "heap_mb",
    "db_p99", "disk_read_latency", "disk_write_latency",
    "error_rate", "gc_pause_p99", "cache_hit_rate", "cache_miss_rate",
    "active_connections", "network_errors",
    "p50_latency", "p95_latency", "p99_latency",
    "queue_lag", "retry_count_per_request", "rps",
    "upstream_timeout_rate", "circuit_breaker_state",
    "http_4xx_rate", "http_5xx_rate", "iops_utilization",
    "thread_pool_queue", "cpu_saturation",
    "db_connection_pool", "db_connection_wait",
]

LOG_FEATURE_COLS = [
    "log_count", "log_max_severity", "log_critical_count",
    "log_has_exception", "log_has_novel_template",
]

CLASSIFIER_META_COLS = ["episode_id", "failure_mode", "timestamp", "elapsed_s"]
ALL_CLASSIFIER_COLS  = CLASSIFIER_META_COLS + RAW_METRIC_FEATURE_COLS + LOG_FEATURE_COLS

# ── Preliminary Severity thresholds ──────────────────────────────────────────
SEVERITY_P1 = {"cpu_utilization": 90, "memory_utilization": 90, "p99_latency": 1000, "log_critical_count": 5, "error_rate": 0.10}
SEVERITY_P2 = {"cpu_utilization": 80, "memory_utilization": 80, "p99_latency": 700,  "error_rate": 0.05, "gc_pause_p99": 200, "log_has_exception": 1}
SEVERITY_P3 = {"cpu_utilization": 60, "p99_latency": 400, "error_rate": 0.02, "cache_miss_rate": 0.50}

# ── Redis transport ───────────────────────────────────────────────────────────
REDIS_HOST = "localhost"
REDIS_PORT = 6379
REDIS_DB   = 0
REDIS_KEY  = "telemetry.raw"

# ── Statistical constants ─────────────────────────────────────────────────────
BASE_RPS         = 200.0
DB_CAPACITY_RPS  = 250.0

# ── Service topology ─────────────────────────────────────────────────────────
ALL_MODES = [
    "NONE", "MEMORY_LEAK", "CPU_SATURATION", "LATENCY_SPIKE",
    "ERROR_STORM", "DB_SLOWDOWN", "CACHE_STAMPEDE", "QUEUE_BACKUP",
    "DEPENDENCY_TIMEOUT", "BAD_DEPLOY", "RETRY_STORM",
    "DISK_IO_SATURATION", "CASCADING_FAILURE",
]

SERVICES            = ["auth-service", "payment-service", "order-service", "inventory-service"]
SERVICE_VERSIONS    = ["v1.0.0", "v1.1.0", "v1.2.3", "v2.0.1"]
DOWNSTREAM_SERVICES = ["user-db", "payment-gateway", "cache-cluster", "inventory-api"]

METRIC_FIELDS = [
    "episode_id", "failure_mode", "service", "source", "elapsed_s", "timestamp",
    "active_connections", "cache_hit_rate", "cache_miss_rate", "circuit_breaker_state",
    "cpu_saturation", "cpu_utilization", "db_connection_pool", "db_connection_wait",
    "db_p99", "disk_read_latency", "disk_write_latency", "error_rate", "gc_pause_p99",
    "heap_mb", "http_4xx_rate", "http_5xx_rate", "iops_utilization", "memory_utilization",
    "network_errors", "p50_latency", "p95_latency", "p99_latency", "queue_lag",
    "retry_count_per_request", "rps", "thread_pool_queue", "upstream_timeout_rate",
]

LOG_FIELDS = [
    "episode_id", "failure_mode", "service", "elapsed_s", "timestamp",
    "log_level", "exception_type", "log_message",
]

TRACE_FIELDS = [
    "episode_id", "failure_mode", "service", "elapsed_s", "timestamp",
    "span_id", "parent_span_id", "span_name", "db_operation_type",
    "span_duration_ms", "span_status", "peer_service", "service_version", "trace_id",
]

LOG_LEVELS = {
    "NONE": "INFO", "MEMORY_LEAK": "WARNING", "CPU_SATURATION": "WARNING",
    "LATENCY_SPIKE": "WARNING", "ERROR_STORM": "ERROR", "DB_SLOWDOWN": "WARNING",
    "CACHE_STAMPEDE": "WARNING", "QUEUE_BACKUP": "WARNING",
    "DEPENDENCY_TIMEOUT": "ERROR", "BAD_DEPLOY": "ERROR",
    "RETRY_STORM": "WARNING", "DISK_IO_SATURATION": "WARNING",
    "CASCADING_FAILURE": "CRITICAL",
}

EXCEPTION_MAP = {
    "ERROR_STORM": "RuntimeException", "DEPENDENCY_TIMEOUT": "SocketTimeoutException",
    "BAD_DEPLOY": "NullPointerException", "CASCADING_FAILURE": "SystemOverloadException",
}

HEALTHY_BASELINE = {
    "cpu_utilization": 22.0, "memory_utilization": 0.25, "heap_mb": 510.0,
    "p50_latency": 90.0, "p95_latency": 110.0, "p99_latency": 130.0,
    "throughput_rps": 200.0, "error_rate": 0.01, "cache_hit_ratio": 0.95,
    "cache_miss_ratio": 0.05, "db_query_latency": 21.0, "db_connections": 120,
    "gc_pause_ms": 15.0, "disk_read_mbps": 5.0, "disk_write_mbps": 6.5,
    "network_errors": 2, "cb_open_ratio": 0.0,
}

CONFORMANCE_THRESHOLD = 0.50

# ── Classifier Hyperparameter Tuning (Optuna) ─────────────────────────────────
# All tuning constants live here.  No magic numbers in train_classifier.py.

# Number of Optuna TPE trials to run.  More = better search quality, but longer.
# 80 is a practical sweet-spot that converges well for a 9-parameter LightGBM search.
TUNING_N_TRIALS: int = 80

# Stratified cross-validation folds.  5 keeps each fold at 20 % of training data,
# giving stable per-class F1 estimates across all 13 failure modes.
TUNING_CV_FOLDS: int = 5

# Wall-clock time cap in seconds (None = run all N_TRIALS, no cap).
# Set to e.g. 600 to hard-limit tuning to 10 minutes.
TUNING_TIMEOUT_SEC: int | None = None

# sklearn metric name and averaging strategy.
# "f1" with "macro" = equal weight to all 13 classes regardless of frequency.
TUNING_METRIC: str = "f1"
TUNING_AVERAGE: str = "macro"

# Reproducibility seed shared by Optuna sampler, StratifiedKFold, and train/val split.
TUNING_RANDOM_SEED: int = 42

# LightGBM stops adding trees once validation F1 has not improved for this many rounds.
# Prevents overtraining.  Recommended: 10–20 % of n_estimators upper bound.
TUNING_EARLY_STOPPING_ROUNDS: int = 50

# Optuna study name (used when persisting to SQLite so studies are resumable).
TUNING_STUDY_NAME: str = "lgbm_incident_f1"

# SQLite database path for persisting the Optuna study.
# Allows resuming an interrupted tuning run without losing completed trials.
TUNING_STUDY_DB: str = str(NODES_DIR / "classification" / "models" / "optuna_study.db")

# LightGBM device type for accelerated fitting.
# "gpu"  – uses NVIDIA CUDA GPU (requires lightgbm built with GPU support).
# "cpu"  – standard CPU training (always available).
# Controlled at runtime via the --gpu CLI flag; this is the fallback default.
TUNING_DEVICE_TYPE: str = "cpu"

# ── LangGraph Pipeline Runtime ────────────────────────────────────────────────
# Milliseconds between DB polling cycles when no new telemetry row is ready.
POLL_INTERVAL_MS: int = 100

# Run the forecasting node once every N pipeline cycles.
# This avoids running expensive ARIMA/time-series models on every 2-second tick.
# Default: 10 cycles = every 20 seconds of telemetry.
FORECAST_EVERY_N_CYCLES: int = 10

# SQLite file for LangGraph checkpointing (SqliteSaver).
# Stores full state after each node so an interrupted run can resume mid-episode.
LANGGRAPH_CHECKPOINT_DB: str = str(NODES_DIR / "classification" / "models" / "langgraph_checkpoints.db")

# Verbose console output for the LangGraph runner (False = clean, True = per-node dicts).
LANGGRAPH_VERBOSE: bool = False

# ── Live Feed Simulator ───────────────────────────────────────────────────────
# Separate DB so live feed never corrupts historical simulator_db.sqlite
LIVE_FEED_DIR           = BACKEND_DIR / "Simulator" / "live_feed_simulator"
LIVE_FEED_DB_PATH       = LIVE_FEED_DIR / "output" / "live_feed_db.sqlite"
LIVE_FEED_OUTPUT_DIR    = LIVE_FEED_DIR / "output"

# Tick interval for live feed (0.5s = 4x faster than historical 2.0s batch)
# 1 episode = 120 ticks × 0.5s = 60 seconds wall time
LIVE_STEP_INTERVAL_S: float = 0.5

# LangGraph poll interval when LiveTelemetryQueue is empty (live mode)
LIVE_POLL_INTERVAL_MS: int = 500


def build_log_msg(mode: str, vals: dict) -> str:
    v = vals
    msgs = {
        "NONE":               "OK cpu={cpu:.0f}% p99={p99:.0f}ms err={err:.2f}%".format(**v),
        "MEMORY_LEAK":        "WARN heap={heap:.0f}MB gc_p99={gc:.0f}ms -- memory leak".format(**v),
        "CPU_SATURATION":     "WARN cpu={cpu:.0f}% -- saturated p99={p99:.0f}ms".format(**v),
        "LATENCY_SPIKE":      "WARN p99={p99:.0f}ms gc_p99={gc:.0f}ms -- latency spike".format(**v),
        "ERROR_STORM":        "ERROR err={err:.2f}% http5xx={h5:.2f}% -- error storm".format(**v),
        "DB_SLOWDOWN":        "WARN db_p99={db:.0f}ms -- slow query detected".format(**v),
        "CACHE_STAMPEDE":     "WARN cache_miss={miss:.0f}% db_p99={db:.0f}ms -- stampede".format(**v),
        "QUEUE_BACKUP":       "WARN queue_lag={lag}ms thread_pool={tp} -- queue backup".format(**v),
        "DEPENDENCY_TIMEOUT": "ERROR upstream_timeout={ut:.2f}% p99={p99:.0f}ms".format(**v),
        "BAD_DEPLOY":         "ERROR err={err:.2f}% http5xx={h5:.2f}% -- bad canary deploy".format(**v),
        "RETRY_STORM":        "WARN retry_cnt={rc:.2f} rps={rps:.0f} -- retry storm".format(**v),
        "DISK_IO_SATURATION": "WARN disk_read={dr:.0f}ms iops={iops:.0f}% -- disk saturation".format(**v),
        "CASCADING_FAILURE":  "CRITICAL cpu={cpu:.0f}% err={err:.2f}% p99={p99:.0f}ms -- cascade".format(**v),
    }
    return msgs.get(mode, f"{mode} detected")
